# Generated by Django 4.2 on 2025-04-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_add_initial_data'),
        ('portfolio', 'add_initial_data'),
    ]

    operations = [
    ]
